version: '3.8'

services:
  auth-tokens:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: am-auth-tokens
    ports:
      - "8080:8080"
    env_file:
      - .env.docker
    volumes:
      - .:/app
    networks:
      - am-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "python", "-c", "import requests; requests.get('http://localhost:8080/health')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    depends_on:
      - user-management

  # Mock user management service for development/testing
  user-management:
    image: nginx:alpine
    container_name: am-user-management-mock
    ports:
      - "8000:80"
    volumes:
      - ./mock-user-service.conf:/etc/nginx/conf.d/default.conf
    networks:
      - am-network
    restart: unless-stopped

networks:
  am-network:
    driver: bridge

volumes:
  auth_data: