version: '3.8'

services:
  auth-tokens:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: am-auth-tokens
    ports:
      - "8080:8080"
    environment:
      # Connect to real am-user-management on host
      - USER_SERVICE_URL=http://host.docker.internal:8000
      - ENVIRONMENT=docker-hybrid
      - DEBUG=true
      - JWT_SECRET=docker-jwt-super-secret-key-production-ready-2025
      - JWT_ALGORITHM=HS256
      - JWT_EXPIRE_MINUTES=1440
      - API_V1_STR=/api/v1
      - PROJECT_NAME=Auth Tokens Service
      - VERSION=1.0.0
      - HOST=0.0.0.0
      - PORT=8080
    volumes:
      - .:/app
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "python", "-c", "import requests; requests.get('http://localhost:8080/health')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  auth_data: