version: '3.8'

services:
  auth-tokens:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: am-auth-tokens
    ports:
      - "8000:8000"
    environment:
      - ENVIRONMENT=development
      - DEBUG=true
      - JWT_SECRET=your-super-secret-jwt-key-change-this-in-production
      - JWT_EXPIRE_MINUTES=1440  # 24 hours
      - USER_SERVICE_URL=http://am-user-management:8001
    volumes:
      - .:/app
    networks:
      - am-network
    depends_on:
      - user-management
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "python", "-c", "import requests; requests.get('http://localhost:8000/health')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Mock user management service for development
  user-management:
    image: nginx:alpine
    container_name: am-user-management-mock
    ports:
      - "8001:80"
    volumes:
      - ./mock-user-service.conf:/etc/nginx/conf.d/default.conf
    networks:
      - am-network
    restart: unless-stopped

networks:
  am-network:
    driver: bridge

volumes:
  auth_data: